services:
  - type: web
    name: askmynotes
    runtime: python
    buildCommand: pip install --no-cache-dir -r requirements.txt
    startCommand: python3 app.py
    envVars:
      - key: GROQ_API_KEY
        sync: false
